[package]
name = "modem-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.5"
serialport = "4.4.0"
log = "0.4.22"
once_cell = "1.19.0"
crossterm = "0.28.1"
ratatui = "0.28.0"
strum = "0.26.3"
strum_macros = "0.26.4"
color-eyre = "0.6.3"
